### ISSUE TITLE
显示出错

### ISSUE THREAD

**Issue by 13691525793** [totond/PictureProgressBar#2]
,试着用了一下,不知道为什么下载文件的进度条,设置max,和progress之后每次这个框架都是走很短的一段,然后就从头重新开始,进度条走不到尽头.纠结了
![s70629-143455 1](https://user-images.githubusercontent.com/26587938/27674412-3c86ca2c-5cd8-11e7-8e24-30f2eb21d1dd.jpg)

**Comment by totond** [comment]
有没有可能是，在下载的时候，你调用setProgress(int progress)这个方法的时候输入了一个负数的参数呢？因为这样的话会导致进度归零。

**Comment by 13691525793** [comment]
从我打印出来的log看，没有出现负数 
------------------ Original ------------------

**Comment by totond** [comment]
是所有动画模式都出现这样的问题吗？你那样打出来的log在进度条重新走的时候的Progress值是多少呢？感觉这样聊有点麻烦，我老是看不到github的提醒，你可以加一下我QQ3475245250交流一下。

**Comment by totond** [comment]
问题已经解决，等一下会更新版本，谢谢帮忙发现bug
